---
title: "Projects"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Project 1: Stepping Stones Report

In the first half of the semester, while we're learning more about R, reproducible data workflows, and ethical data practices, we'll contribute to work for the City of Charlottesville to expand and enrich a community "Stepping Stones" report, a collection of 39 metrics to gauge well-being in Charlottesville and Albemarle. Working in teams, we'll divide up the metrics and build scripts to download updated measures, process them and combine them with the past data series, visualize and better contextualize changes over time. If we do our work well, it will make future iterations of this report easier to generate.

### Project Schedule

* Week 1 (due midnight Jan 25): Individuals skim through the most recent Stepping Stones document and, on a shared project sheet, identify their top choices for the collection of measures they'd like to work on. We'll form into teams during class on Jan 26; each team is responsible for a collection of measures.
* Week 2 (due by class Feb 2): Teams submit initial R script to download assigned measures. Separately, teams submit a 1-2 paragraphs identifying potential policy changes or contexts that might be relevant for assigned measures and warrant further investigation.
* Week 3 (due by class Feb 9): Teams submit revised script to download assigned measures, due any needed processing, and bind them to the prior data series.
* Week 4 (due by class Feb 16): Teams submit revised script to download measures, implement any needed procesing, bind them to the prior data series, and create initial visualizatons. Teams also submit 1-3 paragraph outlinign further details on any relevant policy changes or contexts. 
* Week 5 (due by class Feb 23): Teams submit final version of script to download measures, implement any processing, and bind them to the prior data series. Teams submit initial R markdown file to read in the updated series, visualize them, and incorporate relevant changes or context. Teams will briefly share/show the knitted markdown file in class.
* Week 6 (due by class Mar 2): Teams submit revised R markdown file to read in the updated series, visualize them, and incorporate relevant changes or context.

**Once complete, we'll add all files to Equity Center GitHub and the html report files to the class webpage.** 

## Project 2: Multiple Equity Center Projects

In the second half of the semester, we'll divide up into new teams each working on a different project hosted by The Equity Center. These include projects centered on

* Eviction filings, based on Virginia Civil Court data
* Police stops, based on the Virginia Community Policy Act data collection
* Local rental markets, based on local tax assessment data
* Humanizing data, expanding the Orange Dot report with household profiles using American Community Survey public-use microdata
* A few others we're still sussing out

### Project Schedule

The timelines of these projects will vary more widely as the projects prgress, but a few key targets for all teams will include

* Week 1 (due by midnight Mar 15): Individuals read through the brief project scopes (TBA) and, on a shared project sheet, identify their top choices for projects they'd like to work on. We'll form into teams during class on Mar 16.
* Week 2 (due by class Mar 23): Teams submit an initial R script to download, read in, and explore primary data. Teams submit an initial list of at least three relevant citations to review -- these might be research articles, think tank reports, book chapters, news articles, or something else.
* Week 3 (due by class Mar 30): Teams submit revised script to begin wrangling data and continue data exploration. Teams submit brief reviews of previously suggested materials.
* Week 4 (due by class Apr 6): Teams submit initial R markdown file to share for peer feedback, including description of question, of available data, explorations of processed data, narrative and ideas drawn from initial literature review, and anything else that makes sense at this time. Teams will pair up in class to present to one another and provide thoughtful feedback.
* Week 5 (due by class Apr 13): Updates to data preparation scripts and analysis/presentation R markdown files. Teams submit a new list of at least three additional relevant citations to review.
* Week 6 (due by class Apr 20): Updates to data preparation scripts and analysis/presentation R markdown files. Teams submit brief reviews of newly suggested materials.
* Week 7 (due by class Apr 27): Updates to data preparation scripts and analysis/presentation R markdown files. Teams use R markdown files to present (almost) final work to class.
* Week 8 (due by May 4, in lieu of a final): Teams submit final version of R script to download, process and wrangle data. Teams submit final R markdown and knitted html files to analyze, visualize, and interpret data.

**Once complete, we'll add all files to Equity Center GitHub and the html report files to the class webpage.** 
